[tool.poetry]
name = "actions-central"
version = "0.1.0"
description = ""
authors = ["chickendining <sumethsiripakorn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
