name: Central Composite Workflow

inputs:
  caller_repo:
    description: "Repo name from the caller"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Central Repository
      shell: bash
      run: |
        git clone https://github.com/chickendining/simple-workflow-repo.git central_repo

    - name: Checkout Caller Repository
      shell: bash
      run: |
        git clone https://github.com/${{ inputs.caller_repo }} caller_repo

    # - name: Checkout Caller Repository
    #   shell: bash
    #   uses: actions/checkout@v2
    #   with:
    #     repository: ${{ inputs.caller_repo }}
    #     path: "caller_repo"
    # - name: Setup Python
    #   shell: bash
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.9

    # - name: Install Poetry
    #   shell: bash
    #   run: |
    #     curl -sSL https://install.python-poetry.org | python3 -
    #     echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    #     poetry --version

    # - name: Install project dependencies
    #   shell: bash
    #   run: poetry install
    #   working-directory: central_repo

    - name: List all files and directories
      shell: bash
      run: ls -a

    # - name: Run main.py script
    #   shell: bash
    #   run: poetry run python src/main.py
    #   working-directory: central_repo
