name: Central Reusable Workflow

on:
  workflow_call:
    inputs:
      file_path:
        description: "Path to the file"
        required: true
        type: string

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo File Path
        run: echo "d"
